services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "8080:8080"  # Expose the web app port
    volumes:
      - .:/app # Mount data directory for live updates
    environment:
      - PYTHONUNBUFFERED=1
    # Comment this line for running the container interactively 
    command:
      - gunicorn
      - -k
      - gevent
      - -w
      - "4"
      - -b
      - "0.0.0.0:8080"
      - api:app


    # Uncomment the following lines if you want to run the container interactively
    # tty: true
    # stdin_open: true